[package]
name = "server"
version = "0.1.0"
authors = ["H3nr1X <39547478+H3nr1X@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camera_capture = "*"
image = "*"
scrap = "*"
repng = "*"
