[package]
name = "client"
version = "0.1.0"
authors = ["H3nr1X <39547478+H3nr1X@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.6.1"
winapi = "0.2.8"
kernel32-sys = "0.2.1"
